#!/bin/bash -ex
# Expects to find ARCHIVE_S3_BUCKET, ARCHIVE_S3_REGION, ARCHIVE_S3_FILE in the env variables

# Special case the filename "latest" and assume it's a link to the latest file
if [ ${ARCHIVE_S3_FILE} == "latest" ]; then
  aws s3 cp --region=${ARCHIVE_S3_REGION} s3://${ARCHIVE_S3_BUCKET}/${ARCHIVE_S3_FILE} /tmp/cloudcontest-archive-latest-version
  ARCHIVE_S3_FILE=$(cat /tmp/cloudcontest-archive-latest-version)
fi

INSTALLDIR="/root/${ARCHIVE_S3_FILE%%.*}"
mkdir -p $INSTALLDIR

aws s3 cp --region=${ARCHIVE_S3_REGION} s3://${ARCHIVE_S3_BUCKET}/${ARCHIVE_S3_FILE} "/tmp/${ARCHIVE_S3_FILE}"
tar --no-same-owner -zxf /tmp/${ARCHIVE_S3_FILE} -C "$INSTALLDIR"
rm "/tmp/${ARCHIVE_S3_FILE}"

# run script to install/post configuration
cd $INSTALLDIR
chmod +x $INSTALLDIR/run.sh
./run.sh
